spring.application.name=scheduler

#ADDED PROPERTIES:
# SQLite connection URL
spring.datasource.url=JDBC:sqlite:clinic.db

# SQLite JDBC driver
spring.datasource.driver-class-name=org.sqlite.JDBC

# ALWAYS run schema.sql on startup
spring.sql.init.mode=always